---
base: 
default:
  jdk: https://s3.amazonaws.com/heroku-jvm-langpack-java/binaries/tomcat/apache-tomcat-7.0.41.tar.gz
  tomcat: http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.41/bin/apache-tomcat-7.0.41.tar.gz
